POSTGRESQL_USERNAME: postgres
POSTGRESQL_PASSWORD: postgres
POSTGRESQL_HOST: 127.0.0.1
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: docdatabase

CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID:
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http://localhost:8085.com
